name: Android CI

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  createArtifacts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Read Go version from project
      run: echo "GO_VERSION=$(grep -E "^de\.felixnuesse\.extract\.goVersion=" gradle.properties | cut -d'=' -f2)"
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Set up Go from gradle.properties
      uses: actions/setup-go@v5
      with:
        go-version: '${{env.GO_VERSION}}'
      id: go
    - name: Setup Android SDK/NDK
      uses: android-actions/setup-android@v3
    - name: Install NDK from gradle.properties
      run: |
        NDK_VERSION="$(grep -E "^de\.felixnuesse\.extract\.ndkVersion=" gradle.properties | cut -d'=' -f2)"
        sdkmanager "ndk;${NDK_VERSION}"
    - name: Build app (Debug)
      run: ./gradlew assembleOssDebug
    - name: Build app (Release)
      run: ./gradlew assembleOssRelease
    - name: Build details
      run: ls -lAog ${{ github.workspace }}/app/build/outputs/apk/oss/*/*-oss-*.apk
    - name: Upload APK (arm)
      uses: actions/upload-artifact@v4
      with:
        name: nightly-armeabi.zip
        path: ${{ github.workspace }}/app/build/outputs/apk/oss/*/*-oss-armeabi-v7a-*.apk
    - name: Upload APK (arm64)
      uses: actions/upload-artifact@v4
      with:
        name: nightly-arm64.zip
        path: ${{ github.workspace }}/app/build/outputs/apk/oss/*/*-oss-arm64-v8a-*.apk
    - name: Upload APK (x86)
      uses: actions/upload-artifact@v4
      with:
        name: nightly-x86.zip
        path: ${{ github.workspace }}/app/build/outputs/apk/oss/*/*-oss-x86-*.apk
    - name: Upload APK (arm)
      uses: actions/upload-artifact@v4
      with:
        name: nightly-x64.zip
        path: ${{ github.workspace }}/app/build/outputs/apk/oss/*/*-oss-x86_64-*.apk
    - name: Upload APK (universal)
      uses: actions/upload-artifact@v4
      with:
        name: nightly-universal.zip
        path: ${{ github.workspace }}/app/build/outputs/apk/oss/*/*-oss-universal-*.apk
        retention-days: 14
