name: Android CI

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  createArtifacts:
    strategy:
      fail-fast: ${{ matrix.buildType == 'Release'}}
      matrix:
        include:
          - buildType: Release
            assetPfx: release
          - buildType: Debug
            assetPfx: debug
    env:
      buildType: ${{ matrix.buildType }}
      assetPfx: ${{ matrix.assetPfx }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Read Go version from project
      run: echo "GO_VERSION=$(grep -E "^de\.felixnuesse\.extract\.goVersion=" gradle.properties | cut -d'=' -f2)"
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Set up Go from gradle.properties
      uses: actions/setup-go@v5
      with:
        go-version: '${{env.GO_VERSION}}'
      id: go
    - name: Setup Android SDK/NDK
      uses: android-actions/setup-android@v3
    - name: Install NDK from gradle.properties
      run: |
        NDK_VERSION="$(grep -E "^de\.felixnuesse\.extract\.ndkVersion=" gradle.properties | cut -d'=' -f2)"
        sdkmanager "ndk;${NDK_VERSION}"
    - name: Build app
      run: ./gradlew assembleOss${{env.buildType}}
    - name: Upload Build Results
      run: |
        ls -lAog ${{ github.workspace }}/app/build/outputs/apk/oss/${{env.assetPfx}}/*-oss-${{env.assetPfx}}*.apk && echo
        ls ${{ github.workspace }}/app/build/outputs/apk/oss/${{env.assetPfx}}/*-oss-${{env.assetPfx}}*.apk | while read -r i; do
          curl -s -F "file=@${i}" https://temp.sh/upload && echo
        done
    - name: Upload APK (arm)
      uses: actions/upload-artifact@v4
      with:
        name: nightly-armeabi-${{env.assetPfx}}
        path: ${{ github.workspace }}/app/build/outputs/apk/oss/${{env.assetPfx}}/*-oss-armeabi-v7a-${{env.assetPfx}}*.apk
        compression-level: 9
    - name: Upload APK (arm64)
      uses: actions/upload-artifact@v4
      with:
        name: nightly-arm64-${{env.assetPfx}}
        path: ${{ github.workspace }}/app/build/outputs/apk/oss/${{env.assetPfx}}/*-oss-arm64-v8a-${{env.assetPfx}}*.apk
        compression-level: 9
    - name: Upload APK (x86)
      uses: actions/upload-artifact@v4
      with:
        name: nightly-x86-${{env.assetPfx}}
        path: ${{ github.workspace }}/app/build/outputs/apk/oss/${{env.assetPfx}}/*-oss-x86-${{env.assetPfx}}*.apk
        compression-level: 9
    - name: Upload APK (arm)
      uses: actions/upload-artifact@v4
      with:
        name: nightly-x64-${{env.assetPfx}}
        path: ${{ github.workspace }}/app/build/outputs/apk/oss/${{env.assetPfx}}/*-oss-x86_64-${{env.assetPfx}}*.apk
        compression-level: 9
    - name: Upload APK (universal)
      uses: actions/upload-artifact@v4
      with:
        name: nightly-universal-${{env.assetPfx}}
        path: ${{ github.workspace }}/app/build/outputs/apk/oss/${{env.assetPfx}}/*-oss-universal-*${{env.assetPfx}}.apk
        compression-level: 9
        retention-days: 14
